# website: https://github.com/daattali/beautiful-jekyll
#theme: jekyll-theme-architect
remote_theme: daattali/beautiful-jekyll@5.0.0

title: TK's Playing Ground
description: Place to try various things related to static websites
github:
  is_project_page: false

navbar-links:
  Main: "index"